#CI de nivel 03 - disparo automático sempre que outro for concluído. exemplo o deploy


#Nome que vai aparecer la nas opções de paipe
name: 'YFG - PGATS-d9 - Execução por Deploy '

#triggers ou gatilhos de execução
  #gatilho de execução após outro workflow = workflow_run

on:
  workflow_run:
    #qual workflow será monitorado
    workflows: ['YFG - PGATS-d9 - Execução Manual']
    #2º parametrom, o tipo de evento monitorado
    #sempre
    types:
      - completed


#criar sequencias de fluxos de trabalhos.
#descrição dos jobs
jobs:
  e2e-tests:
    #máquina que o job vai executar
    runs-on: ['ubuntu-latest']
    
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    #passo a passo das ações do job
    steps:
    # - run: |
    #     git clone (direction)
      - uses: actions/checkout@v4
      #instalar as dependencias 
      #o node é um dos casos, mas já tá instaldo.
      # - uses: actions/setup-node@v4
        # with: 
          # node-version: list/*
      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependências
        run: yarn 

      - name: Instalando Playwright
        run: yarn playwright install

      - name: Testes E2E (end-to-end)
        run: yarn run e2e

      # passed, failed, cancelled
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with: 
          name: relatorio-de-testes
          path: ./playwright-report
