# CI de Nível 04 - Disparo dentro do fluxo de CI de desenvolvimento
#2138

# nome que vai aparecer la nas opções de pipe
name: 'YFG - PGATS-d9 - Execução Integrada'

# regras de disparo da execucao (triggers/gatilhos)
# gatilho de exec manual = workflow_dispatch

on: workflow_dispatch
# inspecao
#   padronizacao (formatacao de código)
# testes 💜
#   unidade
#   e2e 💜
#     build
# deploy

jobs:
  #descriçao
  inspection:
    #maquina que o job vai executar
    runs-on: ['ubuntu-latest']

    #passo a passo
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependencias
        run: yarn

      - name: Padronização de código (Lint)
        run: yarn lint

  unit:
    #maquina que o job vai executar
    runs-on: ['ubuntu-latest']

    #passo a passo
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependencias
        run: yarn

      - name: Testes de Unidade
        run: yarn run test

  #descriçao
  e2e-tests:
    #maquina que o job vai executar
    runs-on: ['ubuntu-latest']

    #passo a passo
    steps:
      - uses: actions/checkout@v4

      - name: Instalando Yarn
        run: npm install -g yarn

      - name: Instalando dependencias
        run: yarn

      - name: Instalando Playwright
        run: yarn playwright install

      # vamos subir a aplicacao aqui
      - name: Subir aplicacao local
        run: yarn start &

      - name: Testes E2E (end-to-end)
        run: yarn run e2e
        env:
          URL: 'http://localhost:3000'

      # disponibilizando relatorio (artefato)
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: relatorio-E2E
          path: ./playwright-report
